---
abstract: 'Easy fixtures with DBIx::Class'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires:
  Capture::Tiny: 0
  Carp::Always: 0.13
  DBD::SQLite: 1.39
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  DateTime: 0
  DateTime::Format::SQLite: 0.11
  Test::More: 0
  Test::Most: 0
  base: 0
  lib: 0
  strict: 0
  utf8: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-EasyFixture
requires:
  Carp: 0
  DBIx::Class: 0.08000
  List::MoreUtils: 0.33
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Scalar::Util: 0
  Storable: 0
  aliased: 0
  namespace::autoclean: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/Ovid/dbix-class-easyfixture/issues
  homepage: https://github.com/Ovid/dbix-class-easyfixture
  repository: https://github.com/Ovid/dbix-class-easyfixture.git
version: 0.11
